// Tokyo & 關東常用地區 — shared by 美食清單新增/編輯、篩選與已讚好詳情

export type TokyoArea = { id: string; zh: string; en: string }

export type TokyoDistrict = {
  id: string
  label: string
  en: string
  icon: string
  areas: TokyoArea[]
}

export const TOKYO_DISTRICTS: TokyoDistrict[] = [
  {
    id: 'east',
    label: '東東京',
    en: 'East Tokyo',
    icon: '🏮',
    areas: [
      { id: 'asakusa', zh: '浅草', en: 'Asakusa' },
      { id: 'ueno', zh: '上野', en: 'Ueno' },
      { id: 'akihabara', zh: '秋葉原', en: 'Akihabara' },
      { id: 'yanaka', zh: '谷根千', en: 'Yanaka' },
      { id: 'kuramae', zh: '蔵前', en: 'Kuramae' },
      { id: 'kiyosumishirakawa', zh: '清澄白河', en: 'Kiyosumi-Shirakawa' },
      { id: 'ryogoku', zh: '両国', en: 'Ryogoku' },
      { id: 'kinshicho', zh: '錦糸町', en: 'Kinshicho' },
      { id: 'kitasenju', zh: '北千住', en: 'Kita-Senju' },
      { id: 'sumida', zh: '墨田', en: 'Sumida' },
      { id: 'koto', zh: '江東', en: 'Koto' },
      { id: 'arakawa', zh: '荒川', en: 'Arakawa' },
      { id: 'katsushika', zh: '葛飾', en: 'Katsushika' },
    ],
  },
  {
    id: 'shibuya_area',
    label: '渋谷エリア',
    en: 'Shibuya Area',
    icon: '🛍️',
    areas: [
      { id: 'shibuya', zh: '渋谷', en: 'Shibuya' },
      { id: 'harajuku', zh: '原宿', en: 'Harajuku' },
      { id: 'omotesando', zh: '表参道', en: 'Omotesando' },
      { id: 'aoyama', zh: '青山', en: 'Aoyama' },
      { id: 'ebisu', zh: '恵比寿', en: 'Ebisu' },
      { id: 'daikanyama', zh: '代官山', en: 'Daikanyama' },
      { id: 'nakameguro', zh: '中目黒', en: 'Nakameguro' },
      { id: 'setagaya', zh: '世田谷', en: 'Setagaya' },
      { id: 'meguro', zh: '目黒', en: 'Meguro' },
      { id: 'ota', zh: '大田', en: 'Ota' },
      { id: 'nakano', zh: '中野', en: 'Nakano' },
    ],
  },
  {
    id: 'shinjuku_area',
    label: '新宿エリア',
    en: 'Shinjuku Area',
    icon: '🌃',
    areas: [
      { id: 'shinjuku', zh: '新宿', en: 'Shinjuku' },
      { id: 'shimokitazawa', zh: '下北沢', en: 'Shimokitazawa' },
      { id: 'sangenjaya', zh: '三軒茶屋', en: 'Sangenjaya' },
      { id: 'jiyugaoka', zh: '自由が丘', en: 'Jiyugaoka' },
      { id: 'futakotamagawa', zh: '二子玉川', en: 'Futakotamagawa' },
    ],
  },
  {
    id: 'central',
    label: '都心',
    en: 'Central Tokyo',
    icon: '🏙️',
    areas: [
      { id: 'ginza', zh: '銀座', en: 'Ginza' },
      { id: 'tsukiji', zh: '築地', en: 'Tsukiji' },
      { id: 'shimbashi', zh: '新橋', en: 'Shimbashi' },
      { id: 'nihonbashi', zh: '日本橋', en: 'Nihonbashi' },
      { id: 'yurakucho', zh: '有楽町', en: 'Yurakucho' },
      { id: 'marunouchi', zh: '丸の内', en: 'Marunouchi' },
      { id: 'otemachi', zh: '大手町', en: 'Otemachi' },
    ],
  },
  {
    id: 'minato',
    label: '港区',
    en: 'Minato',
    icon: '🌆',
    areas: [
      { id: 'roppongi', zh: '六本木', en: 'Roppongi' },
      { id: 'akasaka', zh: '赤坂', en: 'Akasaka' },
      { id: 'azabujuban', zh: '麻布十番', en: 'Azabu-Juban' },
      { id: 'hiro', zh: '広尾', en: 'Hiro' },
    ],
  },
  {
    id: 'north',
    label: '北エリア',
    en: 'North Area',
    icon: '🎓',
    areas: [
      { id: 'ikebukuro', zh: '池袋', en: 'Ikebukuro' },
      { id: 'kagurazaka', zh: '神楽坂', en: 'Kagurazaka' },
      { id: 'iidabashi', zh: '飯田橋', en: 'Iidabashi' },
      { id: 'jimbocho', zh: '神保町', en: 'Jimbocho' },
      { id: 'ochanomizu', zh: '御茶ノ水', en: 'Ochanomizu' },
      { id: 'kanda', zh: '神田', en: 'Kanda' },
      { id: 'kita', zh: '北区', en: 'Kita' },
      { id: 'itabashi', zh: '板橋', en: 'Itabashi' },
      { id: 'nerima', zh: '練馬', en: 'Nerima' },
    ],
  },
  {
    id: 'west',
    label: '西エリア',
    en: 'West Area',
    icon: '🌿',
    areas: [
      { id: 'kichijoji', zh: '吉祥寺', en: 'Kichijoji' },
      { id: 'koenji', zh: '高円寺', en: 'Koenji' },
      { id: 'ogikubo', zh: '荻窪', en: 'Ogikubo' },
    ],
  },
  {
    id: 'bay',
    label: '湾岸',
    en: 'Bay Area',
    icon: '🌊',
    areas: [
      { id: 'toyosu', zh: '豊洲', en: 'Toyosu' },
      { id: 'odaiba', zh: '台場', en: 'Odaiba' },
      { id: 'shinagawa', zh: '品川', en: 'Shinagawa' },
    ],
  },
  {
    id: 'suburbs',
    label: '郊外',
    en: 'Suburbs',
    icon: '🌸',
    areas: [
      { id: 'machida', zh: '町田', en: 'Machida' },
      { id: 'tachikawa', zh: '立川', en: 'Tachikawa' },
    ],
  },
  {
    id: 'fuji_yamanashi',
    label: '富士・山梨',
    en: 'Mt.Fuji & Yamanashi',
    icon: '🗻',
    areas: [
      { id: 'fuji', zh: '富士山', en: 'Mount Fuji' },
      { id: 'kawaguchiko', zh: '河口湖', en: 'Kawaguchiko' },
      { id: 'fujiyoshida', zh: '富士吉田', en: 'Fujiyoshida' },
      { id: 'gotemba', zh: '御殿場', en: 'Gotemba' },
      { id: 'yamanakako', zh: '山中湖', en: 'Lake Yamanaka' },
    ],
  },
  {
    id: 'hakone_izu',
    label: '箱根・熱海',
    en: 'Hakone & Izu',
    icon: '♨️',
    areas: [
      { id: 'hakone', zh: '箱根', en: 'Hakone' },
      { id: 'atami', zh: '熱海', en: 'Atami' },
      { id: 'ito', zh: '伊東', en: 'Ito' },
    ],
  },
  {
    id: 'kanagawa_trip',
    label: '神奈川（鎌倉・橫濱）',
    en: 'Kanagawa',
    icon: '⚓',
    areas: [
      { id: 'yokohama', zh: '橫濱', en: 'Yokohama' },
      { id: 'kawasaki', zh: '川崎', en: 'Kawasaki' },
      { id: 'kamakura', zh: '鎌倉', en: 'Kamakura' },
      { id: 'enoshima', zh: '江之島', en: 'Enoshima' },
      { id: 'zushi', zh: '逗子', en: 'Zushi' },
      { id: 'miura', zh: '三浦', en: 'Miura' },
    ],
  },
  {
    id: 'tochigi_nagano',
    label: '日光・長野方面',
    en: 'Nikko & Nagano area',
    icon: '⛰️',
    areas: [
      { id: 'nikko', zh: '日光', en: 'Nikko' },
      { id: 'karuizawa', zh: '輕井澤', en: 'Karuizawa' },
      { id: 'matsumoto', zh: '松本', en: 'Matsumoto' },
      { id: 'hakuba', zh: '白馬', en: 'Hakuba' },
    ],
  },
  {
    id: 'chiba_airport',
    label: '千葉・機場・迪士尼',
    en: 'Chiba, airports & Disney',
    icon: '✈️',
    areas: [
      { id: 'narita', zh: '成田', en: 'Narita' },
      { id: 'chiba', zh: '千葉', en: 'Chiba' },
      { id: 'tokyo_disney', zh: '東京迪士尼', en: 'Tokyo Disney Resort' },
      { id: 'makuhari', zh: '幕張', en: 'Makuhari' },
    ],
  },
  {
    id: 'gunma_saitama',
    label: '群馬・埼玉',
    en: 'Gunma & Saitama',
    icon: '🎿',
    areas: [
      { id: 'takasaki', zh: '高崎', en: 'Takasaki' },
      { id: 'kusatsu', zh: '草津', en: 'Kusatsu' },
      { id: 'kawagoe', zh: '川越', en: 'Kawagoe' },
      { id: 'omiya', zh: '大宮', en: 'Omiya' },
      { id: 'chichibu', zh: '秩父', en: 'Chichibu' },
    ],
  },
  {
    id: 'kansai',
    label: '關西（京・阪・奈）',
    en: 'Kansai (Kyoto, Osaka, Nara)',
    icon: '⛩️',
    areas: [
      { id: 'kyoto_station', zh: '京都車站', en: 'Kyoto Station' },
      { id: 'arashiyama', zh: '嵐山', en: 'Arashiyama' },
      { id: 'gion', zh: '祇園', en: 'Gion' },
      { id: 'fushimi', zh: '伏見', en: 'Fushimi' },
      { id: 'nishiki', zh: '錦市場', en: 'Nishiki Market' },
      { id: 'shinsaibashi', zh: '心齋橋', en: 'Shinsaibashi' },
      { id: 'namba', zh: '難波', en: 'Namba' },
      { id: 'umeda', zh: '梅田', en: 'Umeda' },
      { id: 'dotonbori', zh: '道頓堀', en: 'Dotonbori' },
      { id: 'nara', zh: '奈良', en: 'Nara' },
      { id: 'kobe', zh: '神戶', en: 'Kobe' },
      { id: 'kix_airport', zh: '關西機場', en: 'Kansai Airport' },
    ],
  },
  {
    id: 'chubu',
    label: '中部（名古屋・石川）',
    en: 'Chubu (Nagoya, Ishikawa)',
    icon: '🏯',
    areas: [
      { id: 'nagoya', zh: '名古屋', en: 'Nagoya' },
      { id: 'kanazawa', zh: '金澤', en: 'Kanazawa' },
      { id: 'shirakawa', zh: '白川郷', en: 'Shirakawa-go' },
      { id: 'toyama', zh: '富山', en: 'Toyama' },
      { id: 'niigata', zh: '新潟', en: 'Niigata' },
    ],
  },
  {
    id: 'tohoku',
    label: '東北（仙台・青森）',
    en: 'Tohoku (Sendai, Aomori)',
    icon: '🌾',
    areas: [
      { id: 'sendai', zh: '仙台', en: 'Sendai' },
      { id: 'aomori', zh: '青森', en: 'Aomori' },
      { id: 'akita', zh: '秋田', en: 'Akita' },
      { id: 'yamagata', zh: '山形', en: 'Yamagata' },
      { id: 'fukushima', zh: '福島', en: 'Fukushima' },
      { id: 'hachimantai', zh: '八幡平', en: 'Hachimantai' },
    ],
  },
  {
    id: 'hokkaido_okinawa',
    label: '北海道・沖繩',
    en: 'Hokkaido & Okinawa',
    icon: '❄️',
    areas: [
      { id: 'sapporo', zh: '札幌', en: 'Sapporo' },
      { id: 'otaru', zh: '小樽', en: 'Otaru' },
      { id: 'niseko', zh: '二世古', en: 'Niseko' },
      { id: 'hakodate', zh: '函館', en: 'Hakodate' },
      { id: 'asahikawa', zh: '旭川', en: 'Asahikawa' },
      { id: 'naha', zh: '那霸', en: 'Naha' },
      { id: 'churaumi', zh: '美麗海水族館', en: 'Churaumi' },
    ],
  },
]

export const TOKYO_AREAS: TokyoArea[] = TOKYO_DISTRICTS.flatMap(d => d.areas)
